2019-07-28 17:09:44,169 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:10:03,621 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
2019-07-28 17:37:16,762 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/request.py[line:21] - ERROR: 请求 http://api.nnzhp.cn/api/user/reg的时候出错了，请求参数是：{'username': 'caozn66777', 'pwd': 'aA123456', 'cpwd': 'aA123456'}，错误信息是 Traceback (most recent call last):
  File "/Users/nhy/PycharmProjects/cnz/day10/utp/utlis/request.py", line 19, in req
    response = requests.request(self.method,self.url,params=self.data,data=self.data,headers=self.headers).json()
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 891, in json
    return complexjson.loads(self.text, **kwargs)
  File "/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

2019-07-28 17:37:17,329 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:37:35,005 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
2019-07-28 17:38:21,325 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:38:26,781 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
2019-07-28 17:41:29,951 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:41:30,354 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
2019-07-28 17:42:50,734 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:42:50,927 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
2019-07-28 17:43:32,419 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:43:32,584 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
2019-07-28 17:44:20,622 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:44:27,973 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
2019-07-28 17:45:48,567 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:17] - DEBUG: 开始发送邮件
2019-07-28 17:45:49,998 - /Users/nhy/PycharmProjects/cnz/day10/utp/utlis/tools.py[line:32] - INFO: 发送邮件成功
